### ISSUE TITLE
Track is not downloaded

### ISSUE THREAD

**Issue by davesen83** [clawoo/gexporter-ios#3] opened 2019-04-27 09:16 UTC
When I try to download a gpx track with gimporter, it seems that connection will be closed to early from gexporter, even when gimporter is still downloading the track:

[DEBUG] Did open connection on socket 5
[DEBUG] Did connect
[DEBUG] Did start background task
[DEBUG] Connection received 223 bytes on socket 5
[DEBUG] Connection on socket 5 preflighting request "GET /Lucendro" with 223 bytes body
[DEBUG] Connection on socket 5 processing request "GET /Lucendro" with 223 bytes body
[DEBUG] Connection sent 261 bytes on socket 5
[DEBUG] Connection sent 2834 bytes on socket 5
[DEBUG] Did close connection on socket 5
[VERBOSE] [::1:22222] ::1:49824 200 "GET /Lucendro" (223 | 3095)
**[DEBUG] Did disconnect
[DEBUG] Did end background task**

Another log:
[DEBUG] Did open connection on socket 5
[DEBUG] Did connect
[DEBUG] Did start background task
[DEBUG] Connection received 319 bytes on socket 5
[DEBUG] Connection on socket 5 preflighting request "GET /Leckihorn" with 319 bytes body
[DEBUG] Connection on socket 5 processing request "GET /Leckihorn" with 319 bytes body
[DEBUG] Connection sent 189 bytes on socket 5
[DEBUG] Did close connection on socket 5
[VERBOSE] [::1:22222] ::1:49799 304 "GET /Leckihorn" (319 | 189)
**[DEBUG] Did disconnect
[DEBUG] Did end background task**

The last "Did disconnect" occurs still when gimporter displays "Downloading". Do you have an idea why?

And sometimes gimporter says, track is already downloaded. But it's not at my track list.

**Comment by alinradut** [comment] 2019-04-28 14:05
What's the real actual size for "/Lucendro"? The app seems to think 3095 bytes (~ 3kb).

The "Did close connection" message does not mean that gexporter closed the connection, it could have been closed by the gimporter app.

In your second log I see that it's returning a 304 Not Modified, so I disabled cache in the latest commit, maybe that interferes with the normal process.

It looks like gimporter has issues with downloading large files (presumably due to the hardware limitations of the garmin devices) so if your GPX/FIT files have a ton of track points/waypoints, that might be the cause. 

I can tell you that the gexporter iOS app does not have any significant issues in serving files of any size, you can test this easily by using Postman or a similar tool and running GET [your ios device IP]:22222/Leckihorn or GET /Lucendro, you should see the entire file being returned.

**Comment by davesen83** [comment] 2019-04-28 14:56
The file is 3kB, this is correct.

> In your second log I see that it's returning a 304 Not Modified, so I disabled cache in the latest commit, maybe that interferes with the normal process.

I still get 304 response with gimporter, also with your last commit. Curiously with Postman not...

When I use [iOS device IP]:22222/Leckihorn?type=GPX I got the correct and hole file I think, that's correct, so it's a problem on gimporter side mhh? Thanks for your help.

```
<?xml` version="1.0" encoding="utf-8" standalone="no"?>
<gpx creator="White Risk" version="1.1" xmlns="http://www.topografix.com/GPX/1/1">
    <trk>
        <name>Leckihorn</name>
        <trkseg>
            <trkpt lat="46.59757364" lon="8.50177516" />
            <trkpt lon="8.50220968" lat="46.59676407" />
            <trkpt lat="46.59245604" lon="8.49906663" />
            <trkpt lat="46.58706776" lon="8.49294042" />
            <trkpt lon="8.49515634" lat="46.58572406" />
            <trkpt lat="46.58493074" lon="8.49537084" />
            <trkpt lon="8.49412721" lat="46.58390127" />
            <trkpt lat="46.58250709" lon="8.49350128" />
            <trkpt lon="8.49360341" lat="46.58107026" />
            <trkpt lon="8.49312366" lat="46.57782602" />
            <trkpt lat="46.57465365" lon="8.49457141" />
            <trkpt lat="46.57103119" lon="8.4971293" />
            <trkpt lon="8.49646549" lat="46.56902712" />
            <trkpt lon="8.49656519" lat="46.56725058" />
            <trkpt lat="46.55058554" lon="8.5008008" />
            <trkpt lat="46.54691074" lon="8.4964007" />
            <trkpt lon="8.49017301" lat="46.54418097" />
            <trkpt lat="46.54400658" lon="8.48911904" />
            <trkpt lon="8.48859288" lat="46.54477701" />
            <trkpt lat="46.54525425" lon="8.48692737" />
            <trkpt lat="46.54491545" lon="8.4840857" />
            <trkpt lat="46.54446752" lon="8.48115402" />
            <trkpt lat="46.54265061" lon="8.47497101" />
            <trkpt lat="46.53907676" lon="8.46431269" />
            <trkpt lon="8.46349995" lat="46.53759727" />
            <trkpt lon="8.46415768" lat="46.53583726" />
            <trkpt lat="46.53806009" lon="8.46615924" />
            <trkpt lat="46.5389051" lon="8.46915551" />
            <trkpt lon="8.47339751" lat="46.5404278" />
            <trkpt lat="46.54251114" lon="8.48106787" />
            <trkpt lat="46.54396612" lon="8.48910116" />
            <trkpt lat="46.54675051" lon="8.49642121" />
            <trkpt lat="46.55071464" lon="8.5008373" />
            <trkpt lat="46.56715397" lon="8.4964143" />
            <trkpt lat="46.57091649" lon="8.49704992" />
            <trkpt lat="46.57781145" lon="8.49304085" />
            <trkpt lat="46.58263127" lon="8.49344714" />
            <trkpt lat="46.58496007" lon="8.49542899" />
            <trkpt lon="8.49272046" lat="46.58700938" />
            <trkpt lon="8.49892436" lat="46.59238904" />
            <trkpt lat="46.59681834" lon="8.50194775" />
        </trkseg>
    </trk>
</gpx>
```

**Comment by davesen83** [comment] 2019-04-30 15:11
I‘ve got an answer from gimporter delevoper: Problem is, that fenix only understand fit files. So his gexporter app for android converts automatically gpx files into fit files.

Is this also possible for you to implement this?

Regards

**Comment by alinradut** [comment] 2019-04-30 15:31
I just checked their [Android GPX->FIT converter](https://github.com/gimportexportdevs/gexporter/blob/master/app/src/main/java/org/surfsite/gexporter/Gpx2Fit.java) and it involves some meticulous XML parsing which I don't really have the time nor the motivation to do.

There don't seem to be any readily available libraries I could integrate to handle it either.

If anyone gets around to do it I will gladly accept the pull request.

**Closed as completed** 2019-04-30 18:54 UTC
